dist: bionic
language: python
python:
  - "3.8"
before_install:
  - pip install pipenv
  - pipenv lock -r -d > Requirements.txt
  - pipenv lock -r  >> Requirements.txt
install:
  - pip install -r Requirements.txt
  - pre-commit install
script:
  - pre-commit run -a -v
